# Generated by Django 2.2.6 on 2019-12-20 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='level1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profilemodel',
            name='level2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profilemodel',
            name='level3',
            field=models.BooleanField(default=False),
        ),
    ]
