# Generated by Django 2.2.4 on 2020-03-07 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200308_0056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='Parent_Category',
        ),
        migrations.RemoveField(
            model_name='article',
            name='catagory',
        ),
        migrations.RemoveField(
            model_name='article',
            name='sub_catagory',
        ),
    ]
