# Generated by Django 2.2.4 on 2020-03-07 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200308_0151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='bottom',
        ),
    ]
