# Generated by Django 2.2.4 on 2020-03-15 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_article_bottom'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='Parent_Category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Parent_Category'),
        ),
        migrations.AddField(
            model_name='article',
            name='catagory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Category'),
            preserve_default=False,
        ),
    ]
