# Generated by Django 2.2.4 on 2020-03-15 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_parent_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent_category',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
