# Generated by Django 2.2.4 on 2020-03-15 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_parent_category_private'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent_category',
            name='private',
            field=models.BooleanField(default=True),
        ),
    ]
