# Generated by Django 2.2.4 on 2020-03-15 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20200315_1715'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parent_category',
            old_name='private',
            new_name='public',
        ),
    ]
