# Generated by Django 2.2.4 on 2020-03-22 16:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0011_auto_20200315_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='Private_Users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
