# Generated by Django 2.2.4 on 2020-03-22 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20200322_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent_category',
            name='Private_Users',
            field=models.ManyToManyField(blank=True, to='core.profileModel'),
        ),
    ]
