# Generated by Django 2.2.4 on 2020-03-22 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20200322_2155'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parent_category',
            options={'ordering': ['-Date'], 'verbose_name_plural': 'Parent Categories'},
        ),
        migrations.AddField(
            model_name='parent_category',
            name='Date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
