# Generated by Django 2.2.4 on 2020-04-04 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_parent_category_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent_category',
            name='description',
            field=models.TextField(max_length=500),
        ),
    ]
